import { Oswald } from "next/font/google";
import "./globals.css";
import Fotter from "./comp/Fotter";
import Nav from "./comp/Nav";
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: [ "300", "400", "500", "600", "700"], // كل الأوزان المتاحة
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${oswald.variable} antialiased`}>
        <Nav></Nav>
        {children}
        <Fotter></Fotter>
      </body>
    </html>
  );
}
